### PR TITLE
Automatically download 3D models

### PR DESCRIPTION
**Pull request by corporateshark**
- Automatically download the Khronos 3D models repository (via https://github.com/corporateshark/bootstrapping).
- Load the Sponza model if nothing is specified on the command line.

### CODE REVIEW

**Comment by theWatchmen** [comment]
Just to confirm, with this change users will have to run `git submodule update --init` before being able to run the bootstrap script?

**Comment by corporateshark** [comment]
Right. Or they can clone the entire repo just like this right from the get-go:

`git clone --recurse-submodules https://github.com/PacktPublishing/Mastering-Graphics-Programming-with-Vulkan`

**Comment by theWatchmen** [comment]
Cool. We'll wait to merge this until after the release of the book. I know most people will be able to figure it out, but this change would create a divergence with the instructions in the book and we'd like to avoid confusion :)

**Comment by corporateshark** [comment]
I think this solves the issue #4

**Comment by corporateshark** [comment]
@theWatchmen it looks like there's some strong demand for this.

**Comment by theWatchmen** [comment]
Thanks for this Sergey! I updated the README to include the clone instructions :)

**Pull request merged**
